/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImprintRouteImport } from './routes/legal/imprint'
import { Route as LegalGdprRouteImport } from './routes/legal/gdpr'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalComplaintsRouteImport } from './routes/legal/complaints'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedEnforcementRouteImport } from './routes/_authenticated/enforcement'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCronSyncProvidersRouteImport } from './routes/api/public/cron/sync-providers'
import { Route as ApiPublicV1OrchestrateQuoteRouteImport } from './routes/api/public/v1/orchestrate/quote'

const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalGdprRoute = LegalGdprRouteImport.update({
  id: '/legal/gdpr',
  path: '/legal/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalComplaintsRoute = LegalComplaintsRouteImport.update({
  id: '/legal/complaints',
  path: '/legal/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnforcementRoute =
  AuthenticatedEnforcementRouteImport.update({
    id: '/enforcement',
    path: '/enforcement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronSyncProvidersRoute =
  ApiPublicCronSyncProvidersRouteImport.update({
    id: '/api/public/cron/sync-providers',
    path: '/api/public/cron/sync-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrchestrateQuoteRoute =
  ApiPublicV1OrchestrateQuoteRouteImport.update({
    id: '/api/public/v1/orchestrate/quote',
    path: '/api/public/v1/orchestrate/quote',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drive': typeof DriveRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/enforcement': typeof AuthenticatedEnforcementRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/cron/sync-providers': typeof ApiPublicCronSyncProvidersRoute
  '/api/public/v1/orchestrate/quote': typeof ApiPublicV1OrchestrateQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drive': typeof DriveRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/enforcement': typeof AuthenticatedEnforcementRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/cron/sync-providers': typeof ApiPublicCronSyncProvidersRoute
  '/api/public/v1/orchestrate/quote': typeof ApiPublicV1OrchestrateQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/drive': typeof DriveRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/enforcement': typeof AuthenticatedEnforcementRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/cron/sync-providers': typeof ApiPublicCronSyncProvidersRoute
  '/api/public/v1/orchestrate/quote': typeof ApiPublicV1OrchestrateQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/drive'
    | '/admin'
    | '/enforcement'
    | '/operator'
    | '/provider'
    | '/blog/$slug'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog/'
    | '/api/public/cron/sync-providers'
    | '/api/public/v1/orchestrate/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/drive'
    | '/admin'
    | '/enforcement'
    | '/operator'
    | '/provider'
    | '/blog/$slug'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog'
    | '/api/public/cron/sync-providers'
    | '/api/public/v1/orchestrate/quote'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/drive'
    | '/_authenticated/admin'
    | '/_authenticated/enforcement'
    | '/_authenticated/operator'
    | '/_authenticated/provider'
    | '/blog/$slug'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog/'
    | '/api/public/cron/sync-providers'
    | '/api/public/v1/orchestrate/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DriveRoute: typeof DriveRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalComplaintsRoute: typeof LegalComplaintsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalGdprRoute: typeof LegalGdprRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicCronSyncProvidersRoute: typeof ApiPublicCronSyncProvidersRoute
  ApiPublicV1OrchestrateQuoteRoute: typeof ApiPublicV1OrchestrateQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/gdpr': {
      id: '/legal/gdpr'
      path: '/legal/gdpr'
      fullPath: '/legal/gdpr'
      preLoaderRoute: typeof LegalGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/complaints': {
      id: '/legal/complaints'
      path: '/legal/complaints'
      fullPath: '/legal/complaints'
      preLoaderRoute: typeof LegalComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enforcement': {
      id: '/_authenticated/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof AuthenticatedEnforcementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/sync-providers': {
      id: '/api/public/cron/sync-providers'
      path: '/api/public/cron/sync-providers'
      fullPath: '/api/public/cron/sync-providers'
      preLoaderRoute: typeof ApiPublicCronSyncProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orchestrate/quote': {
      id: '/api/public/v1/orchestrate/quote'
      path: '/api/public/v1/orchestrate/quote'
      fullPath: '/api/public/v1/orchestrate/quote'
      preLoaderRoute: typeof ApiPublicV1OrchestrateQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEnforcementRoute: typeof AuthenticatedEnforcementRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEnforcementRoute: AuthenticatedEnforcementRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DriveRoute: DriveRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalComplaintsRoute: LegalComplaintsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalGdprRoute: LegalGdprRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicCronSyncProvidersRoute: ApiPublicCronSyncProvidersRoute,
  ApiPublicV1OrchestrateQuoteRoute: ApiPublicV1OrchestrateQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
